### ISSUE TITLE
Error Modal not being called in some cases

### ISSUE THREAD

**Issue by gbdubs** [RMI-PACTA/app#168]
I noticed this while working on `userMerge`. Other async operations will return back the error modal if they fail, but not user merge. To reproduce, just enter bogus userIDs + try to merge them. It fails (rightly) but only console logs, and doesn't pop up the error modal.

Would you mind taking a look at this today?

**Comment by bcspragu** [comment]
Went deep on this, general finding is that things triggered "in the background" don't get caught by our error handlers. Removing both the indirection of the `confirm` dialog and the `withLoading` was enough to make it work, but obviously that's not a valid solution, still looking for either 1) how to catch those async errors or 2) how to at least un-async-ify the minimum set of things so we can throw as expected

**Comment by bcspragu** [comment]
This was fixed in #177
