### ISSUE TITLE
Link Button `new-tab` not working

### ISSUE THREAD

**Issue by gbdubs** [RMI-PACTA/app#169]
LinkButtons with new-tab set to true are no longer following the desired behavior: they open in a new tab on the new page, yes, but they also navigate to the new page themselves (defeating the purpose of the new tab). As an example, check out the link to the `/user-guide` from the upload page. 

Would you take a look at this when able?

I've been unable to figure out how/why.

**Comment by bcspragu** [comment]
Discussed offline, looks like this was fixed in a recent PR
