### ISSUE TITLE
"Sign in" button leads to pop-up flow that ends at initial landing page

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/app#205]
## Bug explanation
When accessing the deployed dev version of the application [here](https://pacta.dev.rmi.siliconally.dev/en), I try to access the tool using the sign-in button.

The sign-in triggers a pop-up that prompts me for my info. I fill it out, then a second pop-up window opens for a few moments.
The RMI logo loading icon appears, and I end up at the same landing page. 

## System description
I am accessing the dev deployment of the app here: https://pacta.dev.rmi.siliconally.dev/en
I have tested this on: Brave Browser, Chrome and Safari
I am accessing the app using the jackson.hoffart@gmail.com user account

When inspecting the page source, this is the failure I get in the console: 
<img width="509" alt="Screenshot 2024-07-23 at 14 54 25" src="https://github.com/user-attachments/assets/34b57b05-e4a9-48e3-ad2c-3319522a6e82">

Let me know if I can provide any other helpful info!

**Comment by hodie** [comment]
*probably* related (?): I am seemingly able to sign in but when I got to `https://pacta.dev.rmi.siliconally.dev/en/my-data` or `https://pacta.dev.rmi.siliconally.dev/` I get an empty page that only says "Backend call failure" with the console showing a 500

**Comment by bcspragu** [comment]
Ah, I probably should have mentioned this some where more prominently: only `@rmi.org` and `@siliconally.org` accounts can log in presently. Auth in general definitely needs some work as well

**Comment by jdhoffa** [comment]
Hey @bcspragu, thanks! Confirming both of the above points: 
* Sign-in functions as expected with an `@rmi.org` e-mail
* But navigating to `my-data` results in a "Backend failure", which I guess should be a separate issue. 

Closing this one out :-)
