### ISSUE TITLE
Define/Decide how users answer mandatory questions when uploading files

### ISSUE THREAD

**Issue by hodie** [RMI-PACTA/app#74]
Some initiatives require users to answer initiative-specific questions when uploading files. TBD how this should happen. Most likely something like "click upload > modal with mandatory questions > dialog to actually upload files". But very open to other ideas. @AlexAxthelm do you have description or screenshots of the current flow?

**Comment by AlexAxthelm** [comment]
![Screenshot_2023-12-18_11 05 58@2x](https://github.com/RMI-PACTA/app/assets/2974734/dca008e1-2784-421f-91f6-a88772d55c1e)
Currently the questions are exposed as part of the upload modal itself, alongside the file selection & metadata inputs.

Also note that currently the questions are non-mandatory, so the ability to mark certain questions as required (and others not) would be appreciated.

**Comment by gbdubs** [comment]
A few questions:

1 - Should all portfolios have all of these data populated on them (mandatory?), or should we have them as "other options" on portfolio upload?
2 - Do any of these influence the parsing of the portfolio (i.e. are they needed for the cleaning + standardizing step?)
3 - How often does the set of questions we want to have users answer change?
4 - Should these properties be editable after upload?

**Comment by AlexAxthelm** [comment]
> 1 - Should all portfolios have all of these data populated on them (mandatory?), or should we have them as "other options" on portfolio upload? 

Given that the questions aren't likely to be mandatory or standardized across initiatives, I would suggest these as "other options". On the current system, these are getting saved as a JSON string, and we're processing the questions as needed

> 2 - Do any of these influence the parsing of the portfolio (i.e. are they needed for the cleaning + standardizing step?)

This information is used during analysis, not parsing

> 3 - How often does the set of questions we want to have users answer change?

Rarely. Should be once at initiative setup, but may change a few times after that. I don't expect to need to update existing answers though.

> 4 - Should these properties be editable after upload?

I'll call on @NAYRA-HERRERA and @hodie to discuss this one.

**Comment by cjyetman** [comment]
> > 2 - Do any of these influence the parsing of the portfolio (i.e. are they needed for the cleaning + standardizing step?)
> 
> This information is used during analysis, not parsing

As far as I know, the answers to those questions were only ever used in the creation of the meta-report completely outside of the web app (e.g. neither parsing nor analysis).

**Comment by gbdubs** [comment]
OK sounds like we have consenus on 1-3. Once we know the change schedule, I can finish this out.

**Comment by hodie** [comment]
Unless @cjyetman or @AlexAxthelm disagree, I would say that these can be changed after upload. Mostly because changing them wouldn't require us to rerun any analyses. I'd prefer them being able to correct a response over them re-uploading portfolios just because of an incorrect response.

**Comment by cjyetman** [comment]
I prefer the user being able to change them as well... we just need to manage communication with any potential COP partner that might receive that data in any kind of "meta-analysis" that it is as it was when the data was retrieved.

**Comment by MonikaFu** [comment]
Sorry for being late to the party. I missed this conversation. To my knowledge, so far these questions were not used anywhere in previous COP runs. However, in the current one we will use them (at least) for executive summary and meta analysis. 

I also support the ability for users to change their answers. Maybe making them aware somehow when it is too late to change their answers for being used in meta analysis.

**Comment by AlexAxthelm** [comment]
I think overall, the behavior we need is to be able to disallow changes at some point (when we start doing the meta-analysis). If the easy answer is that users can't change their responses (and have to re-upload/resubmit the portfolio), then I'm okay with that. 

If there's an option to allow changing the answers on an "unsubmitted" portfolio, but once it's submitted, it's locked-in, then that might be the easiest to explain from a user-support perspective.

**Comment by gbdubs** [comment]
I think this is largely done now. We have the ability to set these optionally on creation of a portfolio, and modify them freely afterwards. We also have the capability to detect when they change, and record them alongside runs to test for diffs. If we need a specific locking feature (rather than just rerunning the reports, ex), we can add that in as a separate bug.

**Comment by AlexAxthelm** [comment]
> We have the ability to set these optionally on creation of a portfolio, and modify them freely afterwards. We also have the capability to detect when they change, and record them alongside runs to test for diffs.

So if I'm reading this correctly, the users can change their responses, but we can see the response history?
