### ISSUE TITLE
Make Loading Animation Smaller if the Browser can Handle It (i.e. `webp`)

### ISSUE THREAD

**Issue by gbdubs** [RMI-PACTA/app#8]

**Comment by gbdubs** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

**Comment by gbdubs** [comment]
Hm... the first two online webp converters I tried increased size by 50% (to a bit less than 1MB). @bcspragu do you have a recommended webp converter?

**Comment by bcspragu** [comment]
I played around with a few different formats.

WebP:

```bash
ffmpeg -i logo_loading_animation_v1.gif -vcodec webp -loop 0 -pix_fmt yuv420p -compression_level 6 -lossless 0 -quality 50 test.webp
```

Results in a ~decent looking, 440kb file, not ideal

WebM

```bash
ffmpeg -i logo_loading_animation_v1.gif -c vp9 -b:v 0 -crf 41 test.webm
```

Results in a 55Kb (e.g. 1/10th the size!) video that looks more or less identical:

[test.webm](https://github.com/RMI-PACTA/app/assets/2402010/10302100-b8eb-4635-8c24-3f17f5f6d1e2)

I'll cut a few different formats ([basically like this](https://web.dev/replace-gifs-with-videos/)) and we can use those, probably in order of WebM -> MP4 -> GIF
