### ISSUE TITLE
Look into Custom `Scan` methods

### ISSUE THREAD

**Issue by gbdubs** [RMI-PACTA/app#84]
Quick cleanup across the board: 

https://github.com/RMI-PACTA/app/pull/83#discussion_r1430734203

**Comment by gbdubs** [comment]
OK I looked into this today. The way to do this would be to implement `database/sql.Scanner`, which expects one of a few primitive values. Based on [what I read](https://husobee.github.io/golang/database/2015/06/12/scanner-valuer.html), it looks like the typical use case for implementing DB scanner is when the type is mapped cleanly to a single column. The recommendation for how to do this for multi-column objects is instead to flatten obejects to `[]byte`, the only type flexible enough to be [available in the Scanner package](https://pkg.go.dev/database/sql#Scanner), then to deserialize. That seems to be much messier than the status quo, so I'm going to close this out for now. Thankfully, we don't actually read in any objects in the same way in multiple places (which was the intended goal of the comment) - though we do read in portfoliogroupmemberships in two places, we select different fields depending on the context.

**Comment by bcspragu** [comment]
Sounds good, though if the need arises: We use `pgx`, and `pgx` does support `database/sql.Scanner`, but there's also more advanced, multi-column support directly in `pgtype`, e.g. https://pkg.go.dev/github.com/jackc/pgx/v5@v5.5.1/pgtype#hdr-Overview_of_Scanning_Implementation

**Comment by gbdubs** [comment]
Ahhh that makes much more sense. Thanks Brandon!
